from time import sleep
dia1 = ('Segunda-feira')
dia2 = ('terça-feira')
dia3 = ('quarta-feira')
dia4 = ('Quinta-feira')
dia5 = ('Sexta-feira')
dia6 = ('sábado') 
dia7 = ('domingo')
print('=dias da semana=')
sleep(1)
print(dia1)
sleep(1)
print(dia2)
sleep(1)
print(dia3)
sleep(1)
print(dia4)
sleep(1)
print(dia5)
sleep(1)
print(dia6)
sleep(1)
print(dia7)